import os
import types
import pytest

from tools.web_search import WebSearchTool


def test_summarize_and_improve_heuristic_when_no_client():
    # Ensure no env keys
    os.environ.pop("GOOGLE_API_KEY", None)
    os.environ.pop("GROQ_API_KEY", None)
    tool = WebSearchTool(selected_model="none", provider="none")
    out = tool.summarize_and_improve(
        "# Title\nSome content.", [], style="Tech", goal="")
    assert "# Title" in out or "Improved summary" in out


def test_summarize_and_improve_with_gemini_mock(monkeypatch):
    tool = WebSearchTool(selected_model="gemini-1", provider="google")

    class MockResponse:
        def __init__(self, text):
            self.text = text

    class MockModels:
        def generate_content(self, model, contents):
            return MockResponse("Generated by Gemini")

    class MockClient:
        def __init__(self):
            self.models = MockModels()

    # Inject mock client
    tool.gemini_client = MockClient()
    tool.active_client = tool.gemini_client

    out = tool.summarize_and_improve("# T\ncontent", [], style="S", goal="G")
    assert "Generated by Gemini" in out


def test_summarize_and_improve_uses_production_readme_prompt():
    tool = WebSearchTool(selected_model="gemini-1", provider="google")
    captured = {}

    class MockResponse:
        def __init__(self, text):
            self.text = text

    class MockModels:
        def generate_content(self, model, contents):
            captured["contents"] = contents
            return MockResponse("Generated by Gemini")

    class MockClient:
        def __init__(self):
            self.models = MockModels()

    tool.gemini_client = MockClient()
    tool.active_client = tool.gemini_client

    out = tool.summarize_and_improve("# T\ncontent", [], style="S", goal="G")

    assert "Generated by Gemini" in out
    assert "You are the final Synthesis Agent" in captured["contents"]
    assert "Return ONLY the improved README.md." in captured["contents"]
    assert "Do NOT include \"Suggested Tags\" or badge sections at the top." in captured[
        "contents"] or "Do NOT include \"Suggested Tags\" or badge sections at the top." in captured["contents"]


def test_summarize_and_improve_gemini_fallback_to_groq(monkeypatch):
    tool = WebSearchTool(selected_model="x", provider="google")

    class BadModels:
        def generate_content(self, model, contents):
            raise RuntimeError("gemini down")

    class BadClient:
        def __init__(self):
            self.models = BadModels()

    class MockGroqResponse:
        class Choice:
            class Message:
                def __init__(self):
                    self.content = "Groq fallback content"

        def __init__(self):
            self.choices = [types.SimpleNamespace(
                message=types.SimpleNamespace(content="Groq fallback content"))]

    class MockGroqChat:
        def __init__(self):
            self.completions = types.SimpleNamespace(
                create=lambda model, messages: MockGroqResponse())

    class MockGroqClient:
        def __init__(self):
            self.chat = MockGroqChat()

    tool.gemini_client = BadClient()
    tool.groq_client = MockGroqClient()
    tool.active_client = tool.gemini_client

    out = tool.summarize_and_improve("# T\ncontent", [], style="S", goal="G")
    assert "Groq fallback content" in out


def test_search_similar_repos_tavily_unavailable():
    tool = WebSearchTool()
    # ensure search is None
    tool.search = None
    res = tool.search_similar_repos("query")
    assert res == []


def test_search_similar_repos_with_invoke():
    tool = WebSearchTool()

    class FakeSearch:
        def invoke(self, q):
            return [
                {"title": "Repo A", "url": "http://a", "content": "desc a"},
                {"title": "Repo B", "url": "http://b", "content": "desc b"},
            ]

    tool.search = FakeSearch()
    res = tool.search_similar_repos("q", top_k=1)
    assert isinstance(res, list)
    assert res[0]["title"] == "Repo A"
